### ISSUE TITLE
First load works, then error in pipeline.php

### ISSUE THREAD

**Issue by mprofitlich** [Petertron/asset_pipeline#1]
Hello Petertron and thank you for this extension which I am very happy about. The first time I call the website no problems occur but after that I get the following error:

Symphony Fatal Error: Call to undefined function asset_pipeline\Pipeline::clearDirectory()
An error occurred in /var/www/web149/html/plattform/extensions/asset_pipeline/lib/pipeline.php around line 323

Do you have an idea what I might have done wrong? Thanks for your help.

**Comment by petertron** [comment]
Different PHP versions behave differently -- I have not had the same problem.

I have made a modification which I think will solve the problem, the version number is still the same.

**Comment by mprofitlich** [comment]
Thanks for your quick reply and your time. The error has gone but now nothing loads anymore, not even the backend. I just get empty pages with no html code.

**Comment by petertron** [comment]
Can you tell me what your error log says?

**Comment by mprofitlich** [comment]
Would that be in manifest/logs/main? Only the old error is logged:
18. August 2016 18:49 > Fatal Error: GenericExceptionHandler 1: Call to undefined function \asset_pipeline\Pipeline::clearDirectory() on line 323 of file /var/www/web149/html/plattform/extensions/asset_pipeline/lib/pipeline.php

After updating your extension, no error is being logged.

**Comment by petertron** [comment]
The log I had in mind was your server error log. Anyway, I have made another change.

**Comment by mprofitlich** [comment]
Sorry, of course that one. Thanks a lot for your fix, it works. 

The error in the log was
[Thu Aug 18 19:36:54 2016] [error] [client xx.xxx.xx.xx] PHP Parse error:  syntax error, unexpected '.', expecting ',' or ';' in /var/www/web134/html/plattform/extensions/asset_pipeline/lib/pipeline.php on line 307, referer: http://www.xyz.com/de/dienstleistungen/
