### ISSUE TITLE
Error precompiling assets

### ISSUE THREAD

**Issue by mprofitlich** [Petertron/asset_pipeline#2]
Pipelining files works well now but precompiling does not.

The button `Compile` on page Precompile Assets produces the Javascript alert _Error_ which is scripted as case for a failed Ajax operation. Data seems to be sent however (see below) and the server then returns the same page (without reload).

```
xsrf            j5JBzvQGu+uO/4ZHBfYGVTYlHkE
items[]         stylesheets
items[]         js
action[submit]
```

Also files included on the Settings page of symphony (text field `Precompile Files`) won't be compiled.

Neither symphony's log nor the server's php log show any errors. 

Thanks a lot and sorry for asking for your help again
Moritz

**Comment by petertron** [comment]
No need to apologize! My mistakes must be fixed.
The MD5 hash for the filename was being generated from an empty variable because I used the wrong name. It did not cause an error for me but it might be the reason for the failure you experienced.
Version 0.1.2 has been released.

**Comment by mprofitlich** [comment]
Thanks for your work and your reply. I am afraid I still get the same two errors after I updated the extension (deleted old directory, copied new one, updated): An error message on the page _Precompile Assets_ and only pipelined files although I put the filenames into _Precompile Files_ on the settings page. Still no php or Symphony error. 

Can I do any tests? I am happy to assist.

**Comment by petertron** [comment]
I have made another change. It might make a difference, it might not.

**Comment by mprofitlich** [comment]
It makes a difference: The page _Precompile Assets_ now throws the error _parsererror_ which seems to come from `symphony.min.js` (I searched for this expression with firebug and it only exists in that js file).

The frontend page still outputs pipelined files although I gave filenames in _Precompile Files_.

**Comment by petertron** [comment]
Can you post (attach) your `manifest/asset_pipeline/source-directories.php` file please?

**Comment by mprofitlich** [comment]
Sure! I had to rename it to txt as php was rejected.
[source-directories.txt](https://github.com/Petertron/asset_pipeline/files/435789/source-directories.txt)

```
<?php
return array(

    'stylesheets' => array(
        'name' => 'stylesheets',
        'type' => 'css',
        'precompile_files' => array('style.css'),
    ),

    'js' => array(
        'name' => 'js',
        'type' => 'js',
        'precompile_files' => array('domscript.js'),
    ),

);
```

**Comment by petertron** [comment]
Right, so everything is OK with the file above. The mystery continues.

**Comment by petertron** [comment]
I have made a small but significant change to the AJAX call. I think this is probably the solution.

**Comment by mprofitlich** [comment]
Success! The page _Precompile Assets _ now works. Clicking _Compile_ produces hashed files in the chosen output directory and the frontend delivers them correctly.

However, if I don't precompile the files or delete the precompiled files and _manifest/cache/files-precompiled.php_ the files will be pipelined only although I selected them to be precompiled on the Symphony Settings page. Could you have a look into this as well?

Thank you very much so far!

**Comment by petertron** [comment]
Asset files are not meant to be precompiled automatically. It is for the developer to precompile the assets when a website is ready to be put into production.

**Comment by mprofitlich** [comment]
Thanks Petertron for your expalantion. I am afraid I did not fully understand your manual. The text says _If there is no precompiled version then Asset Pipeline processes the source file if there is any processing to be done_ and _Compilation on page-load is good during development_. I deduced from the explanation that during development files are compiled, too. I guessed that the files listet in _Precompile Files_ would be precompiled. What's that setting for?

It would be helpful to have a checkbox to tell your extension whether the website is in development or production. In development mode the files would be compiled while loading the page with a new hash every time, in production mode they would be compiled once, cached and re-used without a change of the hash. The new hash in development mode would be extemely helpful because my server sets a Cache-Control timeout for every file. For css it is pretty high. I would need to change the cache settings when developing, otherwise the browser would go on using an old, cahed version of the css.

**Comment by petertron** [comment]
Version 0.1.3 has been released. Files compiled on page load now have an MD5 hash.

The reason it is necessary to specify which CSS or JS files are to be precompiled is that not all such files need to be compiled directly. Consider the following manifest file:

```
/*
 * application.css
 *
 *= require reset.css
 *= require main.less
 *= require home.less
 *= require blog.less
 */
```

It is necessary to specify that `application.css` is to be precompiled whereas there is no need to specify that the files listed in `application.css` are to be precompiled.

Earlier versions of Asset Pipeline did have a setting for development/production mode. I decided that there was no need for this feature, and I still do not think there is really a need for this feature.

**Comment by mprofitlich** [comment]
Thanks a lot for your fix and for your explanation. After using yiur extension now a couple of days I agree that a dev mode is not necessary. At the press of the button _compile_ the update is made. Your extension is very useful and helpful.

**Comment by craigerskine** [comment]
After upgrading to Symphony 2.6.8 I get the Parse Error dialog when trying to precompile. I'm using v0.1.3.

**Comment by petertron** [comment]
@craigerskine Can you tell me what your server error log reveals about the matter?

**Comment by craigerskine** [comment]
There's nothing in my error logs for that site. Maybe I don't know how to read them. The second I click the Compile button the error dialog pops... there's no delay. It looks like a JS error dialog but inspecting the page as I click the button does not show any JS errors in the console.

I'm pretty new to Symphony, but I'm getting the hang of it quickly. I have 20+ years experience with web servers and CMS's. I'm trying to switch from TXP to Symphony and the one thing I'm missing is an extension that compresses/hashes the JS/CSS... I found your extension and it looks like just what I need, but I can't seem to get it to work.

I have the directories set up and pointing to the correct places. The production hashes are working... I just need the next step, compiling to static files.

**Comment by craigerskine** [comment]
Update:
I'm not sure what I did but now the Compile button works. Here are the things I did that might have caused it to start working:

1. I was originally working in a subdomain for staging purposes. I've since moved the site into its own permanent domain. I FTP'd the staging files onto my local machine and then FTP'd them to their new home on the server. Maybe the move changed the permissions of the folders... maybe that was the issue the whole time (strange that there were no errors logged and strange that the Compile button did in fact create the folder to store the compiled assets)?

2. I installed the [Cacheable Datasource](https://github.com/symphonists/cacheabledatasource) extension.

3. I cleared out the manifest/cache folder.

4. I added some rules to the .htaccess for single domain redirect and gzip compression.

After all that I just decided to try to compile again and then it worked!

**Comment by petertron** [comment]
@craigerskine Ah, good. The problem you had has prompted me to release an new version which improves the error reporting when precompiling assets.

**Comment by craigerskine** [comment]
I created another site on a subdomain and it fails to compile again. Here's the error:  

    Parse error: syntax error, unexpected '[', expecting ')' in .../content.precompile_assets_ajax.php on line 113

**Comment by petertron** [comment]
@craigerskine I have made an alteration. Your subdomains are using PHP 5.3. The code I used (or copied) for minifying JS used square brackets to define arrays, as allowed in PHP 5.4+.
