### ISSUE TITLE
Compiled JS Assets Destroyed

### ISSUE THREAD

**Issue by craigerskine** [Petertron/asset_pipeline#3]
Compiling assets works fine for CSS but it breaks certain JS scripts like jQuery and most jQuery plugins.

I'm using version 0.1.4 of assets_pipeline on PHP 5.5.3.

**Comment by petertron** [comment]
I've disabled JS minification for now.

**Comment by petertron** [comment]
I have added a new JS minifier. I have not tested it much, but I tried it with JQuery and worked.
