### ISSUE TITLE
JSMin Not found

### ISSUE THREAD

**Issue by craigerskine** [Petertron/asset_pipeline#4]
I get the following error when I try to compile my assets after setup.

```
Fatal error: Class 'AssetPipeline\JSMin' not found in /.../extensions/asset_pipeline/lib/stream/class.APStream.php on line 95
Symphony Fatal Error: Class 'AssetPipeline\JSMin' not found

An error occurred in /.../extensions/asset_pipeline/lib/stream/class.APStream.php around line 95
```

I want my assets served from a 'theme' folder in my workspace folder. My assets are in this structure:

`/workspace/theme/assets-src/css/`
`/workspace/theme/assets-src/img/`
`/workspace/theme/assets-src/js/`

And the output folder:
`/workspace/theme/assets/`

I think I have the settings correct:
![screen shot 2017-04-18 at 7 43 55 am](https://cloud.githubusercontent.com/assets/56437/25131310/da977448-240a-11e7-9eb4-8cd64c7dc1ac.png)

**Comment by petertron** [comment]
Whoops. Version 0.2.1 uploaded.

**Comment by craigerskine** [comment]
Awesome! Works great now. Thank you so much for this extension, it's a much needed piece to Symphony.
